# Import Library

In [1]:
import pandas as pd

# Import Data

In [2]:
df = pd.read_csv('cleaned_order.csv', encoding='utf-8-sig', delimiter=',')
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,Year,Month,MonthName,Quarter
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30,2010,12,December,4
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12,December,4
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00,2010,12,December,4
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12,December,4
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12,December,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
406824,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680,France,10.20,2011,12,December,4
406825,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,France,12.60,2011,12,December,4
406826,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France,16.60,2011,12,December,4
406827,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France,16.60,2011,12,December,4
406828,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France,14.85,2011,12,December,4

In [3]:
print(df.dtypes)

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID       int64
Country         object
Revenue        float64
Year             int64
Month            int64
MonthName       object
Quarter          int64
dtype: object

In [4]:
df['CustomerID']=df["CustomerID"].astype("Int64")
df['CustomerID']=df["CustomerID"].astype(object)
df['InvoiceDate']=pd.to_datetime(df['InvoiceDate'])

In [5]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,Year,Month,MonthName,Quarter
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30,2010,12,December,4
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12,December,4
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00,2010,12,December,4
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12,December,4
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12,December,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
406824,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680,France,10.20,2011,12,December,4
406825,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,France,12.60,2011,12,December,4
406826,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France,16.60,2011,12,December,4
406827,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France,16.60,2011,12,December,4
406828,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France,14.85,2011,12,December,4

In [6]:
print(df.dtypes)

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID             object
Country                object
Revenue               float64
Year                    int64
Month                   int64
MonthName              object
Quarter                 int64
dtype: object

In [7]:
print(df['CustomerID'].nunique())

4372

In [8]:
print(df['StockCode'].nunique())

3684

# Customer

In [9]:
customer_country = (
    df[['CustomerID', 'Country']]
    .dropna(subset=['CustomerID'])
    .drop_duplicates(subset=['CustomerID'])
)
print(customer_country)
customer_country.to_csv('For Database/customer.csv', index=False)

       CustomerID         Country
0           17850  United Kingdom
9           13047  United Kingdom
26          12583          France
46          13748  United Kingdom
65          15100  United Kingdom
...           ...             ...
403812      13436  United Kingdom
403893      15520  United Kingdom
404640      13298  United Kingdom
405385      14569  United Kingdom
406688      12713         Germany

[4372 rows x 2 columns]

# Product

In [10]:
product = (
    df[['StockCode', 'Description', 'UnitPrice']]
    .dropna(subset=['StockCode'])
    .drop_duplicates(subset=['StockCode'])
)
print(product)
product.to_csv('For Database/product.csv', index=False)

       StockCode                          Description  UnitPrice
0         85123A   WHITE HANGING HEART T-LIGHT HOLDER       2.55
1          71053                  WHITE METAL LANTERN       3.39
2         84406B       CREAM CUPID HEARTS COAT HANGER       2.75
3         84029G  KNITTED UNION FLAG HOT WATER BOTTLE       3.39
4         84029E       RED WOOLLY HOTTIE WHITE HEART.       3.39
...          ...                                  ...        ...
397681    90214U            LETTER "U" BLING KEY RING       0.29
397683    90214W            LETTER "W" BLING KEY RING       0.29
397685    90214Z            LETTER "Z" BLING KEY RING       0.29
399525     90089       PINK CRYSTAL SKULL PHONE CHARM       0.19
406349     23843          PAPER CRAFT , LITTLE BIRDIE       2.08

[3684 rows x 3 columns]

# Order Detail

In [11]:
detail_order = (
    df[['InvoiceNo', 'StockCode', 'Quantity', 'UnitPrice']]
    .dropna(subset=['InvoiceNo'])
    .copy()
)
print(detail_order)
detail_order.to_csv('For Database/detail_order.csv', index=False)

       InvoiceNo StockCode  Quantity  UnitPrice
0         536365    85123A         6       2.55
1         536365     71053         6       3.39
2         536365    84406B         8       2.75
3         536365    84029G         6       3.39
4         536365    84029E         6       3.39
...          ...       ...       ...        ...
406824    581587     22613        12       0.85
406825    581587     22899         6       2.10
406826    581587     23254         4       4.15
406827    581587     23255         4       4.15
406828    581587     22138         3       4.95

[406829 rows x 4 columns]

# Order

In [12]:
order = (
    df[['InvoiceNo', 'InvoiceDate', 'CustomerID']]
    .dropna(subset=['InvoiceNo'])
    .drop_duplicates(subset=['InvoiceNo'])
)
print(order)

       InvoiceNo         InvoiceDate CustomerID
0         536365 2010-12-01 08:26:00      17850
7         536366 2010-12-01 08:28:00      17850
9         536367 2010-12-01 08:34:00      13047
21        536368 2010-12-01 08:34:00      13047
25        536369 2010-12-01 08:35:00      13047
...          ...                 ...        ...
406785    581583 2011-12-09 12:23:00      13777
406787    581584 2011-12-09 12:25:00      13777
406789    581585 2011-12-09 12:31:00      15804
406810    581586 2011-12-09 12:49:00      13113
406814    581587 2011-12-09 12:50:00      12680

[22190 rows x 3 columns]

In [13]:
# Hitung total per invoice
invoice_total = (
    detail_order
    .groupby('InvoiceNo')
    .apply(lambda x: (x['Quantity'] * x['UnitPrice']).sum())
)

# Tambahkan kolom Total ke order
order['Total'] = order['InvoiceNo'].map(invoice_total).fillna(0)

# Simpan ke CSV
order.to_csv('For Database/orders.csv', index=False)

C:\Users\DS\AppData\Local\Temp\ipykernel_18940\2381723693.py:5: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: (x['Quantity'] * x['UnitPrice']).sum())